:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Api
dotnet build src\Api
echo Now, run the following to start the project: dotnet run -p src\Api\Api.csproj --launch-profile web.
echo.
